name: Build and Deploy Zola site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Copy blog files
        run: |
          cp -r ./blog/* .github/zola/

      - name: Build with Zola (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/getzola/zola:v0.21.0
          options: -v ${{ github.workspace }}/.github/zola:/site
          run: zola build --root /site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .github/zola/public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
